{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "KS-SQL2018;Reporting_Kart",
        "connectionString": "Provider=SQLNCLI11;Data Source=KS-SQL2018;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=Reporting_Kart",
        "impersonationMode": "impersonateAccount",
        "account": "KSINT\\3349ltk",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "KS Ung Indikatorer",
        "columns": [
          {
            "name": "Demokrati og politikk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Demokrati og politikk",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Befolkning og demografi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Befolkning og demografi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Økonomi og arbeidsliv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Økonomi og arbeidsliv",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "KS Ung Indikatorer",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>134</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Areal (km²)",
            "expression": [
              "",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Areal (km²)\")",
              ")",
              "",
              "return areal"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere 0-15 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in {",
              "\"0 år\",",
              "\"1 år\",",
              "\"2 år\",",
              "\"3 år\",",
              "\"4 år\",",
              "\"5 år\",",
              "\"6 år\",",
              "\"7 år\",",
              "\"8 år\",",
              "\"9 år\",",
              "\"10 år\",",
              "\"11 år\",",
              "\"12 år\",",
              "\"13 år\",",
              "\"14 år\",",
              "\"15 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere 16-18 år",
            "expression": [
              "",
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"16 år\",",
              "\"17 år\",",
              "\"18 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere 19-34 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"19 år\",",
              "\"20 år\",",
              "\"21 år\",",
              "\"22 år\",",
              "\"23 år\",",
              "\"24 år\",",
              "\"25 år\",",
              "\"26 år\",",
              "\"27 år\",",
              "\"28 år\",",
              "\"29 år\",",
              "\"30 år\",",
              "\"31 år\",",
              "\"32 år\",",
              "\"33 år\",",
              "\"34 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere 35-66 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"35 år\",",
              "\"36 år\",",
              "\"37 år\",",
              "\"38 år\",",
              "\"39 år\",",
              "\"40 år\",",
              "\"41 år\",",
              "\"42 år\",",
              "\"43 år\",",
              "\"44 år\",",
              "\"45 år\",",
              "\"46 år\",",
              "\"47 år\",",
              "\"48 år\",",
              "\"49 år\",",
              "\"50 år\",",
              "\"51 år\",",
              "\"52 år\",",
              "\"53 år\",",
              "\"54 år\",",
              "\"55 år\",",
              "\"56 år\",",
              "\"57 år\",",
              "\"58 år\",",
              "\"59 år\",",
              "\"60 år\",",
              "\"61 år\",",
              "\"62 år\",",
              "\"63 år\",",
              "\"64 år\",",
              "\"65 år\",",
              "\"66 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere 67 år og over",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"67 år\",",
              "\"68 år\",",
              "\"69 år\",",
              "\"70 år\",",
              "\"71 år\",",
              "\"72 år\",",
              "\"73 år\",",
              "\"74 år\",",
              "\"75 år\",",
              "\"76 år\",",
              "\"77 år\",",
              "\"78 år\",",
              "\"79 år\",",
              "\"80 år\",",
              "\"81 år\",",
              "\"82 år\",",
              "\"83 år\",",
              "\"84 år\",",
              "\"85 år\",",
              "\"86 år\",",
              "\"87 år\",",
              "\"88 år\",",
              "\"89 år\",",
              "\"90 år\",",
              "\"91 år\",",
              "\"92 år\",",
              "\"93 år\",",
              "\"94 år\",",
              "\"95 år\",",
              "\"96 år\",",
              "\"97 år\",",
              "\"98 år\",",
              "\"99 år\",",
              "\"100 år\",",
              "\"101 år\",",
              "\"102 år\",",
              "\"103 år\",",
              "\"104 år\",",
              "\"105 år eller eldre\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere i alt",
            "expression": [
              "",
              "",
              "[Innbyggere 0-15 år]",
              "+",
              "[Innbyggere 16-18 år]",
              "+",
              "[Innbyggere 19-34 år]",
              "+",
              "[Innbyggere 35-66 år]",
              "+",
              "[Innbyggere 67 år og over]",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere kvinner i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Kjønn'[Dimensjonsnavn]), 'Kjønn'[Dimensjonsnavn] = \"Kvinner\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Innbyggere menn i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Kjønn'[Dimensjonsnavn]), 'Kjønn'[Dimensjonsnavn] = \"Menn\")",
              ")",
              "",
              "return a",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Andel kvinner av befolkningen",
            "expression": [
              "",
              "",
              "([Innbyggere kvinner i alt]",
              "/",
              "[Innbyggere i alt])*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Befolkning og demografi"
          },
          {
            "name": "Andel menn av befolkningen",
            "expression": [
              "",
              "",
              "([Innbyggere menn i alt]",
              "/",
              "[Innbyggere i alt])*100"
            ],
            "formatString": "0.0",
            "displayFolder": "Befolkning og demografi"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "KS Ung Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>134</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Innvandringskategori",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Innvandringskategori",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Innvandringskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Landbakgrunn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Landbakgrunn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Landbakgrunn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kjønn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kjønn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjon 1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Dimensjon 1",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjon 2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Dimensjon 2",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data 1",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Region 1",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a8d63c81-6ac9-4a22-ba78-bc70fc4c6f38",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "04a83c73-ecc9-4ddf-a4df-0b3dcb68a285",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "108fa5b1-b879-41e6-aacc-3e890f95a18d",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "ebbf7bdf-0626-418b-8bf1-4111672de41f",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "1fd5d645-d4be-4ba3-8e3c-9208d2828504",
        "fromTable": "Alle Data",
        "fromColumn": "Dimensjon 1",
        "toTable": "Kjønn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "5288fd8e-96e4-4265-a0aa-4c7677c0824b",
        "fromTable": "Alle Data",
        "fromColumn": "Dimensjon 2",
        "toTable": "Alder",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}