{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "KS-SQL2018;Reporting_Kart",
        "connectionString": "Provider=SQLNCLI11;Data Source=KS-SQL2018;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=Reporting_Kart",
        "impersonationMode": "impersonateAccount",
        "account": "KSINT\\3349ltk",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "KS Ung Indikatorer",
        "columns": [
          {
            "name": "Demokrati og politikk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Demokrati og politikk",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Befolkning og demografi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Befolkning og demografi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Økonomi og arbeidsliv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Økonomi og arbeidsliv",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "KS Ung Indikatorer",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>134</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Areal (km²)",
            "expression": [
              "",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Areal (km²)\")",
              ")",
              "",
              "return areal"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Areal"
          },
          {
            "name": "0-15 år",
            "description": "Antall innbyggere 0-15 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in {",
              "\"0 år\",",
              "\"1 år\",",
              "\"2 år\",",
              "\"3 år\",",
              "\"4 år\",",
              "\"5 år\",",
              "\"6 år\",",
              "\"7 år\",",
              "\"8 år\",",
              "\"9 år\",",
              "\"10 år\",",
              "\"11 år\",",
              "\"12 år\",",
              "\"13 år\",",
              "\"14 år\",",
              "\"15 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "16-18 år",
            "description": "Innbyggere 16-18 år",
            "expression": [
              "",
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"16 år\",",
              "\"17 år\",",
              "\"18 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "19-34 år",
            "description": "Innbyggere 19-34 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"19 år\",",
              "\"20 år\",",
              "\"21 år\",",
              "\"22 år\",",
              "\"23 år\",",
              "\"24 år\",",
              "\"25 år\",",
              "\"26 år\",",
              "\"27 år\",",
              "\"28 år\",",
              "\"29 år\",",
              "\"30 år\",",
              "\"31 år\",",
              "\"32 år\",",
              "\"33 år\",",
              "\"34 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "35-66 år",
            "description": "Innbyggere 35-66 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"35 år\",",
              "\"36 år\",",
              "\"37 år\",",
              "\"38 år\",",
              "\"39 år\",",
              "\"40 år\",",
              "\"41 år\",",
              "\"42 år\",",
              "\"43 år\",",
              "\"44 år\",",
              "\"45 år\",",
              "\"46 år\",",
              "\"47 år\",",
              "\"48 år\",",
              "\"49 år\",",
              "\"50 år\",",
              "\"51 år\",",
              "\"52 år\",",
              "\"53 år\",",
              "\"54 år\",",
              "\"55 år\",",
              "\"56 år\",",
              "\"57 år\",",
              "\"58 år\",",
              "\"59 år\",",
              "\"60 år\",",
              "\"61 år\",",
              "\"62 år\",",
              "\"63 år\",",
              "\"64 år\",",
              "\"65 år\",",
              "\"66 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "67 år og over",
            "description": "Innbyggere 67 år og over",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"67 år\",",
              "\"68 år\",",
              "\"69 år\",",
              "\"70 år\",",
              "\"71 år\",",
              "\"72 år\",",
              "\"73 år\",",
              "\"74 år\",",
              "\"75 år\",",
              "\"76 år\",",
              "\"77 år\",",
              "\"78 år\",",
              "\"79 år\",",
              "\"80 år\",",
              "\"81 år\",",
              "\"82 år\",",
              "\"83 år\",",
              "\"84 år\",",
              "\"85 år\",",
              "\"86 år\",",
              "\"87 år\",",
              "\"88 år\",",
              "\"89 år\",",
              "\"90 år\",",
              "\"91 år\",",
              "\"92 år\",",
              "\"93 år\",",
              "\"94 år\",",
              "\"95 år\",",
              "\"96 år\",",
              "\"97 år\",",
              "\"98 år\",",
              "\"99 år\",",
              "\"100 år\",",
              "\"101 år\",",
              "\"102 år\",",
              "\"103 år\",",
              "\"104 år\",",
              "\"105 år eller eldre\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Folketall",
            "expression": [
              "",
              "",
              "[0-15 år]",
              "+",
              "[16-18 år]",
              "+",
              "[19-34 år]",
              "+",
              "[35-66 år]",
              "+",
              "[67 år og over]",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Folketall"
          },
          {
            "name": "Kvinner i alt",
            "description": "Innbyggere kvinner i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Kjønn'[Dimensjonsnavn]), 'Kjønn'[Dimensjonsnavn] = \"Kvinner\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Menn i alt",
            "description": "Innbyggere menn i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Kjønn'[Dimensjonsnavn]), 'Kjønn'[Dimensjonsnavn] = \"Menn\")",
              ")",
              "",
              "return a",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel kvinner",
            "description": "Andel kvinner av befolkningen",
            "expression": [
              "",
              "",
              "([Kvinner i alt]",
              "/",
              "[Folketall])*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel menn",
            "description": "Andel menn av befolkningen",
            "expression": [
              "",
              "",
              "([Menn i alt]",
              "/",
              "[Folketall])*100"
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel innvandrere og norskfødte med innvandrerforeldre av befolkningen",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(ALL('Landbakgrunn'[Dimensjonsnavn]), 'Landbakgrunn'[Dimensjonsnavn] = \"Alle land\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere og norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Innvandrere i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere\"),",
              "FILTER(all('Landbakgrunn'[Dimensjonsnavn]),'Landbakgrunn'[Dimensjonsnavn] <> \"Alle land\")",
              ")",
              "",
              "",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Personer per privathusholdning",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09747\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer i privathusholdninger\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09747\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Privathusholdninger\")",
              ")",
              "",
              "return DIVIDE(a,b)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Husholdninger"
          },
          {
            "name": "Andel i par, gift*",
            "description": "Samlivsform personer 18 år og over - i par, gift",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"I par, gift\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Andel i par, samboende*",
            "description": "Samlivsform personer 18 år og over - i par, samboende",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"I par, samboende\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Andel ikke i par*",
            "description": "Samlivsform personer 18 år og over - ikke i par",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"Ikke i par\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Nettoinnflytting",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09588\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Nettoinnflytting\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Flytting"
          },
          {
            "name": "Andel primærnæring",
            "description": "Andel virksomheter: Primærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel sekundærnæring",
            "description": "Andel virksomheter: Sekundærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Industri\", \"Bygge- og anleggsvirksomhet\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel uoppgitt næring",
            "description": "Andel virksomheter: Uoppgitt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Uoppgitt\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel tertiærnæring",
            "description": "Andel virksomheter: Tertiærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\", ",
              "\"Industri\", \"Bygge- og anleggsvirksomhet\",",
              "\"Uoppgitt\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE((b-a),b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Innbyggere 0-15 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in {",
              "\"0 år\",",
              "\"1 år\",",
              "\"2 år\",",
              "\"3 år\",",
              "\"4 år\",",
              "\"5 år\",",
              "\"6 år\",",
              "\"7 år\",",
              "\"8 år\",",
              "\"9 år\",",
              "\"10 år\",",
              "\"11 år\",",
              "\"12 år\",",
              "\"13 år\",",
              "\"14 år\",",
              "\"15 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 16-18 år",
            "expression": [
              "",
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"16 år\",",
              "\"17 år\",",
              "\"18 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 19-34 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "{\"19 år\",",
              "\"20 år\",",
              "\"21 år\",",
              "\"22 år\",",
              "\"23 år\",",
              "\"24 år\",",
              "\"25 år\",",
              "\"26 år\",",
              "\"27 år\",",
              "\"28 år\",",
              "\"29 år\",",
              "\"30 år\",",
              "\"31 år\",",
              "\"32 år\",",
              "\"33 år\",",
              "\"34 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 35-66 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"35 år\",",
              "\"36 år\",",
              "\"37 år\",",
              "\"38 år\",",
              "\"39 år\",",
              "\"40 år\",",
              "\"41 år\",",
              "\"42 år\",",
              "\"43 år\",",
              "\"44 år\",",
              "\"45 år\",",
              "\"46 år\",",
              "\"47 år\",",
              "\"48 år\",",
              "\"49 år\",",
              "\"50 år\",",
              "\"51 år\",",
              "\"52 år\",",
              "\"53 år\",",
              "\"54 år\",",
              "\"55 år\",",
              "\"56 år\",",
              "\"57 år\",",
              "\"58 år\",",
              "\"59 år\",",
              "\"60 år\",",
              "\"61 år\",",
              "\"62 år\",",
              "\"63 år\",",
              "\"64 år\",",
              "\"65 år\",",
              "\"66 år\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 67 år og over",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"07459\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] in ",
              "",
              "{\"67 år\",",
              "\"68 år\",",
              "\"69 år\",",
              "\"70 år\",",
              "\"71 år\",",
              "\"72 år\",",
              "\"73 år\",",
              "\"74 år\",",
              "\"75 år\",",
              "\"76 år\",",
              "\"77 år\",",
              "\"78 år\",",
              "\"79 år\",",
              "\"80 år\",",
              "\"81 år\",",
              "\"82 år\",",
              "\"83 år\",",
              "\"84 år\",",
              "\"85 år\",",
              "\"86 år\",",
              "\"87 år\",",
              "\"88 år\",",
              "\"89 år\",",
              "\"90 år\",",
              "\"91 år\",",
              "\"92 år\",",
              "\"93 år\",",
              "\"94 år\",",
              "\"95 år\",",
              "\"96 år\",",
              "\"97 år\",",
              "\"98 år\",",
              "\"99 år\",",
              "\"100 år\",",
              "\"101 år\",",
              "\"102 år\",",
              "\"103 år\",",
              "\"104 år\",",
              "\"105 år eller eldre\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Andel kvinner av befolkningen",
            "expression": [
              "",
              "",
              "([Kvinner i alt]",
              "/",
              "[Folketall])*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel menn av befolkningen",
            "expression": [
              "",
              "",
              "([Menn i alt]",
              "/",
              "[Folketall])*100"
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Samlivsform andel personer 18 år og over - i par, gift*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"I par, gift\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Samlivsform andel personer 18 år og over - i par, samboende*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"I par, samboende\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Samlivsform andel personer 18 år og over - ikke i par*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"06096\"),",
              "FILTER(all('Samlivsform'[Dimensjonsnavn]), 'Samlivsform'[Dimensjonsnavn] = \"Ikke i par\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (prosent)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Samlivsform"
          },
          {
            "name": "Andel virksomheter: Primærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Sekundærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Industri\", \"Bygge- og anleggsvirksomhet\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Tertiærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\", ",
              "\"Industri\", \"Bygge- og anleggsvirksomhet\",",
              "\"Uoppgitt\"})",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE((b-a),b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Uoppgitt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Uoppgitt\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] = \"Alle næringer\")",
              "",
              "",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Sykefraværsprosent 4. kvartal*",
            "expression": [
              "",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"12449\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefraværsprosent 4. kvartal\")",
              ")",
              "",
              "return areal"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sykefravær"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 150 000 - 249 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 150 000 - 249 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 250 000 - 349 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 250 000 - 349 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 350 000 - 449 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 350 000 - 449 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 450 000 - 549 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 450 000 - 549 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 550 000 - 749 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 550 000 - 749 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 750 000 kr og over*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 750 000 kr og over, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt under 150 000 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt under 150 000 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "150 000 - 249 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 150 000 - 249 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "250 000 - 349 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 250 000 - 349 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "350 000 - 449 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 350 000 - 449 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "450 000 - 549 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 450 000 - 549 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "550 000 - 749 999 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 550 000 - 749 999 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "750 000 kr og over*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt 750 000 kr og over, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Under 150 000 kr*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt under 150 000 kr, prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel innvandrere av befolkningen",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere\"),",
              "FILTER(all('Landbakgrunn'[Dimensjonsnavn]),'Landbakgrunn'[Dimensjonsnavn] <> \"Alle land\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Andel norskfødte med innvandrerforeldre av befolkningen",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Andel av befolkningen som ikke er innvandrere og norskfødte med innvandrerforeldre",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere og norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE((b-a),b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Innvandrere",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere\"),",
              "FILTER(all('Landbakgrunn'[Dimensjonsnavn]),'Landbakgrunn'[Dimensjonsnavn] <> \"Alle land\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Norskfødte med innvandrerforeldre",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE(a,b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Øvrige befolkning",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09817\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer\"),",
              "filter(all('Innvandringskategori'[Dimensjonsnavn]),'Innvandringskategori'[Dimensjonsnavn] ",
              "=\"Innvandrere og norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"11342\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Befolkning per 1.1. (personer)\")",
              ")",
              "",
              "return (DIVIDE((b-a),b))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 15-19 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"15-19 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 20-24 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"20-24 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 25-39 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"25-39 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 40-54 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"40-54 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 55-66 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"55-66 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 67-74 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"67-74 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 4. kvartal etter bosted 15-74 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"07984\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sysselsatte personer etter bosted\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"15-74 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå andel personer 16 år og over - grunnskolenivå",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Grunnskolenivå\")",
              ")",
              "",
              "return (divide(a, [Personer med utdanningsnivå]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå andel personer 16 år og over - fagskolenivå",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Fagskolenivå\")",
              ")",
              "",
              "return (divide(a, [Personer med utdanningsnivå]))*100",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå andel personer 16 år og over - universitets- og høgskolenivå, kort",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Universitets- og høgskolenivå, kort\")",
              ")",
              "",
              "return (divide(a, [Personer med utdanningsnivå]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå andel personer 16 år og over - universitets- og høgskolenivå, lang",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Universitets- og høgskolenivå, lang\")",
              ")",
              "",
              "return (divide(a, [Personer med utdanningsnivå]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå personer 16 år og over - uoppgitt/ingen fullført utdanning",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Uoppgitt eller ingen fullført utdanning\")",
              ")",
              "",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "isHidden": true,
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Høyeste fullførte utdanningsnivå andel personer 16 år og over - videregående skolenivå",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Videregående skolenivå\")",
              ")",
              "",
              "return (divide(a, [Personer med utdanningsnivå]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Andel som bor i tettbygd strøk",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"05212\"),",
              "filter(ALL('Tettbygdspredtbygd strøk'[Dimensjonsnavn]), 'Tettbygdspredtbygd strøk'[Dimensjonsnavn] = \"Tettbygd strøk\"),",
              "FILTER(ALL('Kjønn'[Dimensjonsnavn]), 'Kjønn'[Dimensjonsnavn] in {\"Kvinner\", \"Menn\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Folkemengde\")",
              ")",
              "",
              "return (divide (a,[Folketall]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tettbygd"
          },
          {
            "name": "Andel personer med eierstatus selveier",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11038\"),",
              "filter(all('Eierstatus'[Dimensjonsnavn]), 'Eierstatus'[Dimensjonsnavn] = \"Selveier\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall personer\")",
              ")",
              "",
              "return (divide (a,[Personer med eierstatus]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Andel personer med eierstatus andels- / aksjeeier",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11038\"),",
              "filter(all('Eierstatus'[Dimensjonsnavn]), 'Eierstatus'[Dimensjonsnavn] = \"Andels- / aksjeeier\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall personer\")",
              ")",
              "",
              "return (divide (a,[Personer med eierstatus]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Andel personer med eierstatus leier",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11038\"),",
              "filter(all('Eierstatus'[Dimensjonsnavn]), 'Eierstatus'[Dimensjonsnavn] = \"Leier\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall personer\")",
              ")",
              "",
              "return (divide (a,[Personer med eierstatus]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Personer med utdanningsnivå",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Utdanningsnivå i alt\")",
              ")",
              "",
              "var b = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"09429\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer 16 år og over\"),",
              "FILTER(ALL('Nivå'[DimensjonsNavn]), 'Nivå'[DimensjonsNavn] = \"Uoppgitt eller ingen fullført utdanning\")",
              ")",
              "",
              "return a-b"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Personer med eierstatus",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"11038\"),",
              "filter(all('Eierstatus'[Dimensjonsnavn]), 'Eierstatus'[Dimensjonsnavn] =\"I alt\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall personer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Andel av befolkningen som er under 15 år",
            "expression": [
              "",
              "",
              "([Innbyggere 0-15 år]",
              "/",
              "[Folketall])*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Valgdeltakelse Stortingsvalg - prosent*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08243\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgdeltakelse\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Valgdeltakelse"
          },
          {
            "name": "Andel medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (per 1.1)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"12026\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (antall)\")",
              ")",
              "",
              "return (divide (a,[Folketall]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Andel medlemmer og tilhørige i Den norske kirke (per 1.1)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"12026\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer og tilhørige i Dnk (antall)\")",
              ")",
              "",
              "return (divide (a,[Folketall]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Andel som ikke er medlem i DnK eller tros- og livssynssamfunn utenfor DnK (per 1.1)",
            "expression": [
              "",
              "",
              "100-",
              "([Andel medlemmer og tilhørige i Den norske kirke (per 1.1)]+",
              "[Andel medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (per 1.1)])",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Andel medlemmer og tilhørige i DnK og tros- og livssynssamfunn utenfor (per 1.1)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"12026\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] in {\"Medlemmer og tilhørige i Dnk (antall)\",",
              "\"Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (antall)\"})",
              ")",
              "",
              "return (divide (a,[Folketall]))*100"
            ],
            "formatString": "#,0.0",
            "isHidden": true,
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke i alt",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Medlemmer i alt\")",
              "",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke annen religion",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Annan religion\")",
              "",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke buddhisme",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Buddhisme\")",
              "",
              ")",
              "",
              "return a",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke islam",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Islam\")",
              "",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke kristendom",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Kristendom\")",
              "",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke livssyn",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08531\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\"),",
              "filter(all('Religionlivssyn'[Dimensjonsnavn]), 'Religionlivssyn'[Dimensjonsnavn] = \"Livssyn\")",
              "",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Kvadratmeterpris (kr) brukte eneboliger*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"03364\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Kvadratmeterpris (kr)\"),",
              "FILTER(ALL('Type'[Dimensjonsnavn]), 'Type'[Dimensjonsnavn] = \"Brukte eneboliger\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Kvadratmeterpris (kr) nye eneboliger*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"03364\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Kvadratmeterpris (kr)\"),",
              "FILTER(ALL('Type'[Dimensjonsnavn]), 'Type'[Dimensjonsnavn] = \"Nye eneboliger\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Alle lovbruddsgrupper per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Alle lovbruddsgrupper\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Andel netto driftsutgifter til sosialsektoren",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Sosialsektoren samlet\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til barnevern",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Barnevern\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til administrasjon",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Administrasjon, kommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til eiendomsforvaltning",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Eiendomsforvaltning, kommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til barnehage",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Barnehage\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til grunnskole",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Grunnskole\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til helse og omsorg",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12362\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Helse- og omsorg\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return (DIVIDE(a,[Samlede netto driftsutgifter]))*100"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Har kommunen innført eiendomsskatt*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12503\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Har kommunen innført eiendomsskatt? (ja=1, nei=0)\"),",
              "FILTER(ALL('Region'[Kategori]), 'Region'[Kategori] = \"Kommune\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Eiendomsskatt"
          },
          {
            "name": "Hvor mange kommuner i fylket har innført eiendomsskatt*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12503\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Har kommunen innført eiendomsskatt? (ja=1, nei=0)\"),",
              "FILTER(ALL('Region'[Kategori]), 'Region'[Kategori] = \"Fylke\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Eiendomsskatt"
          },
          {
            "name": "Hvor mange kommuner i landet har innført eiendomsskatt*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12503\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Har kommunen innført eiendomsskatt? (ja=1, nei=0)\"),",
              "FILTER(ALL('Region'[Kategori]), 'Region'[Kategori] = \"Landet\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Eiendomsskatt"
          },
          {
            "name": "Annet lovbrudd per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Annet lovbrudd (inkl. Annet vinningslovbrudd, Eiendomsskade og Seksuallovbrudd)\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Eiendomstyveri per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Eiendomstyveri\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Ordens- og integritetskrenkelse per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Ordens- og integritetskrenkelse\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Rusmiddellovbrudd per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Rusmiddellovbrudd\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Trafikkovertredelse per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Trafikkovertredelse\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Vold og mishandling per 1 000 innbyggere (årlig gjennomsnitt)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"08487\"),",
              "FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), 'Lovbruddtype'[Dimensjonsnavn] = \"Vold og mishandling\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Antall virksomheter innen primærnæring",
            "description": "Andel virksomheter: Primærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Antall virksomheter innen sekundærnæring",
            "description": "Andel virksomheter: Sekundærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Industri\", \"Bygge- og anleggsvirksomhet\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Antall virksomheter tertiærnæring",
            "description": "Andel virksomheter: Tertiærnæring",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"10309\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Virksomheter\"),",
              "FILTER(ALL('Antall'[Dimensjonsnavn]), 'Antall'[Dimensjonsnavn] = \"Alle størrelsesgrupper\"),",
              "filter(all('Næring'[Dimensjonsnavn]), 'Næring'[Dimensjonsnavn] in ",
              "{\"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\", ",
              "\"Industri\", \"Bygge- og anleggsvirksomhet\",",
              "\"Uoppgitt\"})",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Valgdeltakelse kommunestyre- og fylkestingsvalg - prosent*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"09475\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgdeltakelse i prosent\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Valgdeltakelse"
          },
          {
            "name": "Valgte repesentanter Arbeiderpartiet*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Arbeiderpartiet\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Fremskrittspartiet*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Fremskrittspartiet\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Høyre*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Høyre\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Senterpartiet*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Senterpartiet\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Sosialistisk Venstreparti*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Sosialistisk Venstreparti\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Venstre*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Venstre\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter andre*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a-[Sum partirepresentanter]"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Sum partirepresentanter",
            "expression": [
              "",
              "",
              "([Valgte repesentanter Arbeiderpartiet*]",
              "+",
              "[Valgte repesentanter Fremskrittspartiet*]",
              "+",
              "[Valgte repesentanter Høyre*]",
              "+",
              "[Valgte repesentanter Senterpartiet*]",
              "+",
              "[Valgte repesentanter Sosialistisk Venstreparti*]",
              "+",
              "[Valgte repesentanter Venstre*]",
              "+",
              "[Valgte repesentanter Kristelig Folkeparti*])"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte repesentanter Kristelig Folkeparti*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "FILTER(ALL('Politisk parti'[Dimensjonsnavn]), 'Politisk parti'[Dimensjonsnavn] = \"Kristelig Folkeparti\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Gjennomsnittlig kvadratmeterpris blokkleiligheter (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06035\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig kvadratmeterpris (kr)\"),",
              "FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Blokkleiligheter\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Gjennomsnittlig kvadratmeterpris eneboliger (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06035\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig kvadratmeterpris (kr)\"),",
              "FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Eneboliger\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Gjennomsnittlig kvadratmeterpris småhus (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06035\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig kvadratmeterpris (kr)\"),",
              "FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Småhus\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Kommunestyremedlemmer 18-29 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"04966\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"18-29 år\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Kommunestyremedlemmer 30-39 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"04966\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"30-39 år\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Kommunestyremedlemmer 40-49 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"04966\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"40-49 år\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Kommunestyremedlemmer 50-59 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"04966\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"50-59 år\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Kommunestyremedlemmer 60 år eller eldre",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"04966\"),",
              "FILTER(ALL('Alder'[Dimensjonsnavn]), 'Alder'[Dimensjonsnavn] = \"60 år eller eldre\"), ",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Medlemmer\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Netto driftsutgifter politisk styring og kontrollvirksomhet (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Politisk styring og kontrollvirksomhet, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter administrasjon (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Administrasjon, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter eiendomsforvaltning (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Eiendomsforvaltning, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter Fellesutgifter (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Fellesutgifter, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter fysisk planlegging, kulturminner, natur, nærmiljø, fylkeskommune (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Fysisk planlegging, kulturminner, natur, nærmiljø, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter kultur (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Kultur, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter næringsforvaltning (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Næringsforvaltning, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter samferdsel (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Samferdsel, fylkeskommune\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter tannhelse (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Tannhelse\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Netto driftsutgifter videregående opplæring samlet (FK)",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12368\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\"),",
              "FILTER(ALL('Funksjon'[Dimensjonsnavn]), 'Funksjon'[Dimensjonsnavn] = \"Videregående opplæring samlet\"),",
              "FILTER(ALL('Art'[Dimensjonsnavn]), 'Art'[Dimensjonsnavn] = \"Netto driftsutgifter på funksjon/tjenesteområde\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Inntekt etter skatt - alle husholdninger, median (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06944\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt, median (kr)\"),",
              "FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), 'Husholdningstype'[Dimensjonsnavn] = \"Alle husholdninger\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Inntekt etter skatt - aleneboende, median (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06944\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt, median (kr)\"),",
              "FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), 'Husholdningstype'[Dimensjonsnavn] = \"Aleneboende\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Inntekt etter skatt - enslig mor/far med barn 0-17 år, median (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06944\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt, median (kr)\"),",
              "FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), 'Husholdningstype'[Dimensjonsnavn] = \"Enslig mor/far med barn 0-17 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Inntekt etter skatt - par med barn 0-17 år, median (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06944\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt, median (kr)\"),",
              "FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), 'Husholdningstype'[Dimensjonsnavn] = \"Par med barn 0-17 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Inntekt etter skatt - par uten barn, median (kr)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06944\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Inntekt etter skatt, median (kr)\"),",
              "FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), 'Husholdningstype'[Dimensjonsnavn] = \"Par uten barn\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Samlede netto driftsutgifter",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"12364\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel uføretrygdede av befolkningen 18-67 år*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer]= \"ØOA01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Andel uføretrygdede av befolkningen 18-67 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Uføretrygdede"
          },
          {
            "name": "Netto driftsutgifter øvrige sektorer",
            "expression": [
              "",
              "",
              "100-",
              "([Andel netto driftsutgifter til administrasjon]",
              "+",
              "[Andel netto driftsutgifter til barnehage]",
              "+",
              "[Andel netto driftsutgifter til barnevern]",
              "+",
              "[Andel netto driftsutgifter til eiendomsforvaltning]",
              "+",
              "[Andel netto driftsutgifter til grunnskole]",
              "+",
              "[Andel netto driftsutgifter til helse og omsorg]",
              "+",
              "[Andel netto driftsutgifter til sosialsektoren])"
            ],
            "formatString": "#,0.0",
            "isHidden": true,
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Antall kommunestyremedlemmer 18-29 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer] = \"DOP01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall kommunestyrerepresentanter 18-29 år\")",
              ")",
              "",
              "return a"
            ],
            "formatString": "#,0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel kommunestyremedlemmer 18-29 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"01182\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Valgte representanter\")",
              ")",
              "",
              "return (DIVIDE([Antall kommunestyremedlemmer 18-29 år],a))*100",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel kommunestyremedlemmer 30 år og over",
            "expression": [
              "",
              "",
              "100-[Andel kommunestyremedlemmer 18-29 år]"
            ],
            "formatString": "0.0",
            "isHidden": true,
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Copy of Antall kommunestyremedlemmer 18-29 år",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), Tabeller[Tabellnummer] = \"DOP01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall kommunestyrerepresentanter 18-29 år\")",
              ")",
              "",
              "return a",
              "",
              "/*Hvordan lage en samlevariabel med kommune + fylke og landet?*/"
            ],
            "formatString": "#,0.0",
            "isHidden": true
          },
          {
            "name": "Siktede personer",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"09418\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Siktede personer, bosted\")",
              ")",
              "",
              "return A"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 5 år+",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"5-151\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 5-14 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"5-14\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 15-17 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"15-17\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 18-20 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"18-20\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 21-24 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"21-24\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 25-29 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"25-29\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 30-39 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"30-39\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 40-49 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"40-49\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 50-59 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"50-59\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer 60-150 år",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"60-150\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer uoppgitt alder",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"160-991\")",
              ")"
            ]
          },
          {
            "name": "Siktede personer i alt",
            "expression": [
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"0-991\")",
              ")"
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "KS Ung Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>134</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Innvandringskategori",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Innvandringskategori",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Innvandringskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Landbakgrunn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Landbakgrunn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Landbakgrunn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kjønn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kjønn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Region 1",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Alder",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Alder",
            "sourceProviderType": "Char"
          },
          {
            "name": "Innvandringskategori",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Innvandringskategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kjønn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kjønn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Landbakgrunn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Landbakgrunn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Samlivsform",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Samlivsform",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Næring",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Næring"
          },
          {
            "name": "Antall",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Antall"
          },
          {
            "name": "Nivå",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nivå"
          },
          {
            "name": "Eierstatus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Eierstatus"
          },
          {
            "name": "Art",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Art"
          },
          {
            "name": "Boligtype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Boligtype"
          },
          {
            "name": "Funksjon",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Funksjon"
          },
          {
            "name": "Husholdningtype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Husholdningtype"
          },
          {
            "name": "Lovbruddstype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Lovbruddstype"
          },
          {
            "name": "Tettbygd/spredtbygd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tettbygd/spredtbygd"
          },
          {
            "name": "Type enebolig",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Type enebolig"
          },
          {
            "name": "Politisk parti",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Politisk parti"
          },
          {
            "name": "Religion/livssyn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Religion/livssyn"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alle Data].[Tabell],[dbo].[Alle Data].[Kode],[dbo].[Alle Data].[Variabel],[dbo].[Alle Data].[Alder],[dbo].[Alle Data].[Antall],[dbo].[Alle Data].[Art],[dbo].[Alle Data].[Boligtype],[dbo].[Alle Data].[Eierstatus],[dbo].[Alle Data].[Funksjon],[dbo].[Alle Data].[Husholdningtype],[dbo].[Alle Data].[Innvandringskategori],[dbo].[Alle Data].[Kjønn],[dbo].[Alle Data].[Landbakgrunn],[dbo].[Alle Data].[Lovbruddstype],[dbo].[Alle Data].[Nivå],[dbo].[Alle Data].[Næring],[dbo].[Alle Data].[Politisk parti],[dbo].[Alle Data].[Religion/livssyn],[dbo].[Alle Data].[Samlivsform],[dbo].[Alle Data].[Tettbygd/spredtbygd],[dbo].[Alle Data].[Type enebolig],[dbo].[Alle Data].[År],[dbo].[Alle Data].[Verdi] FROM [dbo].[Alle Data] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Innvandringskategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Landbakgrunn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>65</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samlivsform</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>51</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Hovedlovbruddtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Innvandringskategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Landbakgrunn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samlivsform</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Hovedlovbruddtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Hovedlovbruddtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].[Tabell],[dbo].[Alle Data].[Kode],[dbo].[Alle Data].[Variabel],[dbo].[Alle Data].[Alder],[dbo].[Alle Data].[Antall],[dbo].[Alle Data].[Art],[dbo].[Alle Data].[Boligtype],[dbo].[Alle Data].[Eierstatus],[dbo].[Alle Data].[Funksjon],[dbo].[Alle Data].[Husholdningtype],[dbo].[Alle Data].[Innvandringskategori],[dbo].[Alle Data].[Kjønn],[dbo].[Alle Data].[Landbakgrunn],[dbo].[Alle Data].[Lovbruddstype],[dbo].[Alle Data].[Nivå],[dbo].[Alle Data].[Næring],[dbo].[Alle Data].[Politisk parti],[dbo].[Alle Data].[Religion/livssyn],[dbo].[Alle Data].[Samlivsform],[dbo].[Alle Data].[Tettbygd/spredtbygd],[dbo].[Alle Data].[Type enebolig],[dbo].[Alle Data].[År],[dbo].[Alle Data].[Verdi] FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alder</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Innvandringskategori</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønn</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Landbakgrunn</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <int>65</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samlivsform</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <int>51</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Hovedlovbruddtype</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <int>102</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alder</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Innvandringskategori</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønn</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Landbakgrunn</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samlivsform</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Hovedlovbruddtype</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Hovedlovbruddtype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Samlivsform",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Samlivsform",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Samlivsform].* FROM [dbo].[Samlivsform] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Samlivsform].* FROM [dbo].[Samlivsform] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Samlivsform"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Antall",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Antall",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Antall].* FROM [dbo].[Antall] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Antall].* FROM [dbo].[Antall] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Antall"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Næring",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Næring",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Næring].* FROM [dbo].[Næring] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Næring].* FROM [dbo].[Næring] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Næring"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Nivå",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Nivå",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Nivå].* FROM [dbo].[Nivå] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Nivå].* FROM [dbo].[Nivå] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Nivå"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Eierstatus",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Eierstatus",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Eierstatus].* FROM [dbo].[Eierstatus] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eierstatus].* FROM [dbo].[Eierstatus] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eierstatus"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Lovbruddtype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Lovbruddtype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Lovbruddtype].* FROM [dbo].[Lovbruddtype] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Lovbruddtype].* FROM [dbo].[Lovbruddtype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Lovbruddtype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Religionlivssyn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Religionlivssyn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Religion/livssyn].* FROM [dbo].[Religion/livssyn] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Religion/livssyn].* FROM [dbo].[Religion/livssyn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Religion/livssyn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tettbygdspredtbygd strøk",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tettbygdspredtbygd strøk",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tettbygd/spredtbygd strøk].* FROM [dbo].[Tettbygd/spredtbygd strøk] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tettbygd/spredtbygd strøk].* FROM [dbo].[Tettbygd/spredtbygd strøk] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tettbygd/spredtbygd strøk"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Type",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Type",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Type].* FROM [dbo].[Type] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Type].* FROM [dbo].[Type] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Type"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Politisk parti",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Politisk parti",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Politisk parti].* FROM [dbo].[Politisk parti] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Politisk parti].* FROM [dbo].[Politisk parti] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Politisk parti"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Boligtype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Boligtype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Boligtype].* FROM [dbo].[Boligtype] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Boligtype].* FROM [dbo].[Boligtype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Boligtype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Husholdningstype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Husholdningstype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Husholdningstype].* FROM [dbo].[Husholdningstype] ",
              "dataSource": "KS-SQL2018;Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Husholdningstype].* FROM [dbo].[Husholdningstype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Husholdningstype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6764c131-70d7-4d58-87ec-e1be7e87721f",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "71e5ce99-7109-4b3e-85ce-575d842bbe34",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "1727a679-fdf9-482d-83d4-8451a729262f",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "3d4b5eaf-52e7-4e30-9098-a92d9cc94cf9",
        "fromTable": "Alle Data",
        "fromColumn": "Innvandringskategori",
        "toTable": "Innvandringskategori",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "9f18fa73-6ce3-4e25-93d3-468f963d45c4",
        "fromTable": "Alle Data",
        "fromColumn": "Kjønn",
        "toTable": "Kjønn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "6573154d-3676-4f48-b81d-4f0475fa2b32",
        "fromTable": "Alle Data",
        "fromColumn": "Landbakgrunn",
        "toTable": "Landbakgrunn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "402eb682-7e33-4464-a1e5-80daaacf08d7",
        "fromTable": "Alle Data",
        "fromColumn": "Samlivsform",
        "toTable": "Samlivsform",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "18bbd2aa-4900-4509-910a-02c976f5c4de",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "6ef723c4-9df4-4e94-af53-3bd46d6baf18",
        "fromTable": "Alle Data",
        "fromColumn": "Næring",
        "toTable": "Næring",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "99f14b80-da20-4da6-9dae-92d750150620",
        "fromTable": "Alle Data",
        "fromColumn": "Antall",
        "toTable": "Antall",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "28370490-a573-48d2-8fd6-180c1f5661db",
        "fromTable": "Alle Data",
        "fromColumn": "Alder",
        "toTable": "Alder",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "8e53a793-df81-45b0-9898-fe026e6e85ce",
        "fromTable": "Alle Data",
        "fromColumn": "Nivå",
        "toTable": "Nivå",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cd997538-c7f8-4545-b944-cb530bfc5432",
        "fromTable": "Alle Data",
        "fromColumn": "Eierstatus",
        "toTable": "Eierstatus",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cff1f54c-2aed-4e71-9908-c2efb18fe322",
        "fromTable": "Alle Data",
        "fromColumn": "Religion/livssyn",
        "toTable": "Religionlivssyn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "ce88a1d2-a620-4b5d-8927-a1aac3af336e",
        "fromTable": "Alle Data",
        "fromColumn": "Tettbygd/spredtbygd",
        "toTable": "Tettbygdspredtbygd strøk",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "b3219bb5-1efd-4319-ba17-6206e4a00997",
        "fromTable": "Alle Data",
        "fromColumn": "Type enebolig",
        "toTable": "Type",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "c6a56284-b0f3-48bb-ab38-78ab6d78f297",
        "fromTable": "Alle Data",
        "fromColumn": "Lovbruddstype",
        "toTable": "Lovbruddtype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "98ffd7f1-93cb-4536-ab6e-d3ea390c1555",
        "fromTable": "Alle Data",
        "fromColumn": "Art",
        "toTable": "Art",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f451768d-7ea2-44b2-8752-8e1f1da0390f",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjon",
        "toTable": "Funksjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "b2b0ecdc-39d0-49bd-a715-5dc7c3c137d0",
        "fromTable": "Alle Data",
        "fromColumn": "Politisk parti",
        "toTable": "Politisk parti",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "d8a23017-8390-4f32-8e8a-97ab382f411a",
        "fromTable": "Alle Data",
        "fromColumn": "Boligtype",
        "toTable": "Boligtype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "929faa59-070f-4de2-9581-4a0bf7211730",
        "fromTable": "Alle Data",
        "fromColumn": "Husholdningtype",
        "toTable": "Husholdningstype",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}