{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "Reporting_Kart",
        "connectionString": "Provider=SQLNCLI11;Data Source=server;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=db",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Region 1",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Alder",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Alder",
            "sourceProviderType": "Char"
          },
          {
            "name": "Innvandringskategori",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Innvandringskategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kjønn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kjønn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Landbakgrunn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Landbakgrunn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Næring",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Næring"
          },
          {
            "name": "Antall",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Antall"
          },
          {
            "name": "Nivå",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nivå"
          },
          {
            "name": "Eierstatus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Eierstatus"
          },
          {
            "name": "Art",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Art"
          },
          {
            "name": "Boligtype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Boligtype"
          },
          {
            "name": "Funksjon",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Funksjon"
          },
          {
            "name": "Husholdningtype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Husholdningtype"
          },
          {
            "name": "Lovbruddstype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Lovbruddstype"
          },
          {
            "name": "Tettbygd/spredtbygd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tettbygd/spredtbygd"
          },
          {
            "name": "Type enebolig",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Type enebolig"
          },
          {
            "name": "Politisk parti",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Politisk parti"
          },
          {
            "name": "Religion/livssyn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Religion/livssyn"
          },
          {
            "name": "Sivilstand",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sivilstand"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Alle Data].[Tabell],[dbo].[Alle Data].[Kode],[dbo].[Alle Data].[Variabel],[dbo].[Alle Data].[Alder],[dbo].[Alle Data].[Antall],[dbo].[Alle Data].[Art],[dbo].[Alle Data].[Boligtype],[dbo].[Alle Data].[Eierstatus],[dbo].[Alle Data].[Funksjon],[dbo].[Alle Data].[Husholdningtype],[dbo].[Alle Data].[Innvandringskategori],[dbo].[Alle Data].[Kjønn],[dbo].[Alle Data].[Landbakgrunn],[dbo].[Alle Data].[Lovbruddstype],[dbo].[Alle Data].[Nivå],[dbo].[Alle Data].[Næring],[dbo].[Alle Data].[Politisk parti],[dbo].[Alle Data].[Religion/livssyn],[dbo].[Alle Data].[Sivilstand],[dbo].[Alle Data].[Tettbygd/spredtbygd],[dbo].[Alle Data].[Type enebolig],[dbo].[Alle Data].[År],[dbo].[Alle Data].[Verdi] FROM [dbo].[Alle Data] ",
              "dataSource": "Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Innvandringskategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Landbakgrunn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>65</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>51</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sivilstand</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Innvandringskategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Landbakgrunn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sivilstand</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Næring</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Antall</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nivå</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierstatus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Art</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Boligtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjon</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sivilstand</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Husholdningtype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lovbruddstype</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Religion/livssyn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Politisk parti</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsomfang</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tettbygd/spredtbygd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Type enebolig</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].[Tabell],[dbo].[Alle Data].[Kode],[dbo].[Alle Data].[Variabel],[dbo].[Alle Data].[Alder],[dbo].[Alle Data].[Antall],[dbo].[Alle Data].[Art],[dbo].[Alle Data].[Boligtype],[dbo].[Alle Data].[Eierstatus],[dbo].[Alle Data].[Funksjon],[dbo].[Alle Data].[Husholdningtype],[dbo].[Alle Data].[Innvandringskategori],[dbo].[Alle Data].[Kjønn],[dbo].[Alle Data].[Landbakgrunn],[dbo].[Alle Data].[Lovbruddstype],[dbo].[Alle Data].[Nivå],[dbo].[Alle Data].[Næring],[dbo].[Alle Data].[Politisk parti],[dbo].[Alle Data].[Religion/livssyn],[dbo].[Alle Data].[Sivilstand],[dbo].[Alle Data].[Tettbygd/spredtbygd],[dbo].[Alle Data].[Type enebolig],[dbo].[Alle Data].[År],[dbo].[Alle Data].[Verdi] FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alder</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Innvandringskategori</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønn</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Landbakgrunn</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <int>65</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <int>51</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sivilstand</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <int>102</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alder</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Innvandringskategori</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønn</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Landbakgrunn</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sivilstand</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Næring</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Antall</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nivå</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierstatus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Art</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Boligtype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjon</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sivilstand</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Husholdningtype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lovbruddstype</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Religion/livssyn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Politisk parti</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsomfang</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tettbygd/spredtbygd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Type enebolig</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "KS Ung Indikatorer",
        "columns": [
          {
            "name": "Demokrati og politikk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Demokrati og politikk",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Befolkning og demografi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Befolkning og demografi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Økonomi og arbeidsliv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Økonomi og arbeidsliv",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Annet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Annet",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "KS Ung Indikatorer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] ",
              "dataSource": "Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>134</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Demokrati og politikk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Befolkning og demografi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Økonomi og arbeidsliv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Annet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Domstolene og kriminalitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Areal (km²)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11342\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Areal (km²)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Areal"
          },
          {
            "name": "Innbyggere 0-19 år",
            "description": "Antall innbyggere 0-15 år",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 0 && VALUE([Dimensjonskode]) <= 19))",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 20-39 år",
            "description": "Innbyggere 16-18 år",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 20 && VALUE([Dimensjonskode]) <= 39))",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 40-59 år",
            "description": "Innbyggere 19-34 år",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 40 && VALUE([Dimensjonskode]) <= 59))",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 60-79 år",
            "description": "Innbyggere 35-66 år",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 60 && VALUE([Dimensjonskode]) <= 79))",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere 80 år og over",
            "description": "Innbyggere 67 år og over",
            "expression": [
              "",
              "",
              "/* 105+ blir ikke fanget av IFen så er lagt til som en ekstra sjekk */",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 80 && VALUE([Dimensjonskode]) <= 104)",
              "        || [Dimensjonskode] = \"105+\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Andel kvinner",
            "description": "Andel kvinner av befolkningen",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Antall kvinner av befolkningen], [Folketall]) * 100, 2)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel menn",
            "description": "Andel menn av befolkningen",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Antall menn av befolkningen], [Folketall]) * 100, 2)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel innvandrere og norskfødte med innvandrerforeldre",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09817\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\"),",
              "    FILTER(ALL('Landbakgrunn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle land\"),",
              "    FILTER(ALL('Innvandringskategori'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Innvandrere og norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Innbyggere per 1.1]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Innvandrere i alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09817\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\"),",
              "    FILTER(ALL('Innvandringskategori'[Dimensjonsnavn]), [Dimensjonsnavn] =",
              "        \"Innvandrere\"",
              "    ),",
              "    FILTER(ALL('Landbakgrunn'[Dimensjonsnavn]), [Dimensjonsnavn] <> ",
              "        \"Alle land\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Personer per privathusholdning",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09747\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer i privathusholdninger\")",
              ")",
              "",
              "var b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09747\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Privathusholdninger\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, b), 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Husholdninger"
          },
          {
            "name": "Gift",
            "description": "Samlivsform personer 18 år og over - i par, gift",
            "expression": [
              "",
              "",
              "var antall_gifte =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Gift\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_gifte, [Folketall]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Ugift",
            "description": "Samlivsform personer 18 år og over - i par, samboende",
            "expression": [
              "",
              "",
              "var antall_ugifte =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Ugift\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_ugifte, [Folketall]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Skilt",
            "description": "Samlivsform personer 18 år og over - ikke i par",
            "expression": [
              "",
              "",
              "var antall_ugifte =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Skilt\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_ugifte, [Folketall]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Nettoinnflytting",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09588\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Nettoinnflytting\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Flytting"
          },
          {
            "name": "Andel virksomheter: Primærnæring",
            "expression": [
              "",
              "",
              "ROUND(",
              "    DIVIDE([Antall virksomheter: Primærnæring], [Antall virksomheter]) * 100,",
              "    2",
              ")",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Sekundærnæring",
            "expression": [
              "",
              "",
              "ROUND(",
              "    DIVIDE([Antall virksomheter: Sekundærnæring], [Antall virksomheter]) * 100,",
              "    2",
              ")",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Tertiærnæring",
            "expression": [
              "",
              "",
              "ROUND(",
              "    DIVIDE([Antall virksomheter: Tertiærnæring], [Antall virksomheter]) * 100,",
              "    2",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Andel virksomheter: Uoppgitt",
            "expression": [
              "",
              "",
              "ROUND(",
              "    DIVIDE([Antall virksomheter: Uoppgitt], [Antall virksomheter]) * 100,",
              "    2",
              ")",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Sykefraværsprosent 4. kvartal",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12449\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefraværsprosent 4. kvartal\")",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sykefravær"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 150 000 - 249 999 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 150 000 - 249 999 kr, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 250 000 - 349 999 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 250 000 - 349 999 kr, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 350 000 - 449 999 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 350 000 - 449 999 kr, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 450 000 - 549 999 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 450 000 - 549 999 kr, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 550 000 - 749 999 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 550 000 - 749 999 kr, prosent\"",
              "    )",
              ")",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt 750 000 kr og over",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt 750 000 kr og over, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel husholdninger med inntekt etter skatt under 150 000 kr",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07182\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt under 150 000 kr, prosent\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Andel innvandrere",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09817\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\"),",
              "    FILTER(ALL('Innvandringskategori'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Innvandrere\"),",
              "    FILTER(ALL('Landbakgrunn'[Dimensjonsnavn]), [Dimensjonsnavn] <> \"Alle land\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Innbyggere per 1.1]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Andel norskfødte med innvandrerforeldre",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09817\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\"),",
              "    FILTER(ALL('Innvandringskategori'[Dimensjonsnavn]), [Dimensjonsnavn] =",
              "        \"Norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Innbyggere per 1.1]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Andel etnisk norske",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09817\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\"),",
              "    FILTER(ALL('Innvandringskategori'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Innvandrere og norskfødte med innvandrerforeldre\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(([Innbyggere per 1.1] - a), [Innbyggere per 1.1]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innvandringskategori"
          },
          {
            "name": "Sysselsatte 15-19 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"15-19 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 20-24 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"20-24 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 25-39 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"25-39 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 40-54 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"40-54 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 55-66 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"55-66 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 67-74 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"67-74 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Sysselsatte 15-74 år",
            "expression": [
              "",
              "",
              "CALCULATE([Sysselsatte i alt],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"15-74 år\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Grunnskole",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Antall personer 16 år og over med grunnskoleutdanning eller høyere],",
              "    FILTER(ALL('Nivå'[DimensjonsNavn]), [DimensjonsNavn] = \"Grunnskolenivå\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, [Antall personer 16 år og over med grunnskoleutdanning eller høyere]) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Fagskole",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Antall personer 16 år og over med grunnskoleutdanning eller høyere],",
              "    FILTER(ALL('Nivå'[DimensjonsNavn]), [DimensjonsNavn] = \"Fagskolenivå\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, [Antall personer 16 år og over med grunnskoleutdanning eller høyere]) * 100,",
              "        2",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Universitets- og høyskole, kort utdanning",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Antall personer 16 år og over med grunnskoleutdanning eller høyere],",
              "    FILTER(ALL('Nivå'[DimensjonsNavn]), [DimensjonsNavn] = ",
              "        \"Universitets- og høgskolenivå, kort\"",
              "    )",
              ")    ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, [Antall personer 16 år og over med grunnskoleutdanning eller høyere]) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Universitets- og høyskole, lang utdanning",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Antall personer 16 år og over med grunnskoleutdanning eller høyere],",
              "    FILTER(ALL('Nivå'[DimensjonsNavn]), [DimensjonsNavn] = ",
              "        \"Universitets- og høgskolenivå, lang\"",
              "    )",
              ")    ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, [Antall personer 16 år og over med grunnskoleutdanning eller høyere]) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Videregående",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Antall personer 16 år og over med grunnskoleutdanning eller høyere],",
              "    FILTER(ALL('Nivå'[DimensjonsNavn]), [DimensjonsNavn] = ",
              "        \"Videregående skolenivå\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, [Antall personer 16 år og over med grunnskoleutdanning eller høyere]) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Andel som bor i tettbygd strøk",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"05212\"),",
              "    FILTER(ALL('Tettbygdspredtbygd strøk'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tettbygd strøk\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] in {\"Kvinner\", \"Menn\"}),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Folkemengde\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Folketall]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tettbygd"
          },
          {
            "name": "Andel personer med eierstatus selveier",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Personer med eierstatus],",
              "    FILTER(ALL('Eierstatus'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Selveier\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Personer med eierstatus]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Andel personer med eierstatus andels- / aksjeeier",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Personer med eierstatus],",
              "    FILTER(ALL('Eierstatus'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Andels- / aksjeeier\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Personer med eierstatus]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Andel personer med eierstatus leier",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE([Personer med eierstatus],",
              "    FILTER(ALL('Eierstatus'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Leier\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Personer med eierstatus]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Personer med eierstatus",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11038\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Antall personer\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Valgdeltakelse Stortingsvalg - prosent",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var valgte_region = SELECTEDVALUE('Region'[Kode])",
              "",
              "var valgdeltakelse = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"08243\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Valdeltaking\")",
              ")",
              "",
              "/* Hvis sammenslåingen har skjedd etter valgte_aar 1, ellers 0 */",
              "var skalnullesut =",
              "CALCULATE([Er regionen sammenslått],",
              "    FILTER(ALL('Region'[Kode]), [Kode] = valgte_region),",
              "    FILTER(ALL('Sammenslåtte Regioner'[GyldigFraDato]), ",
              "        IF(YEAR([GyldigFraDato]) > valgte_aar, 1, 0)",
              "    )",
              ")",
              "",
              "return (",
              "    IF(skalnullesut, 0, valgdeltakelse)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Valgdeltakelse"
          },
          {
            "name": "Andel medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (per 1.1)",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12026\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Folketall]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Andel medlemmer og tilhørige i Den norske kirke (per 1.1)",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Medlemmer og tilhørige i Den norske kirke], [Folketall]) * 100, 2)",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Andel som ikke er medlem i DnK eller tros- og livssynssamfunn utenfor DnK (per 1.1)",
            "expression": [
              "",
              "",
              "var sum_andel = [Andel medlemmer og tilhørige i Den norske kirke (per 1.1)] +",
              "    [Andel medlemmer i tros- og livssynssamfunn utenfor Den norske kirke (per 1.1)]",
              "",
              "return (",
              "    100 - sum_andel",
              ") ",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i tros- og livssynssamfunn utenfor Den norske kirke i alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Medlemmer i alt\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i andre trossamfunn utenfor Den norske kirke",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Annan religion\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i buddhistiske trossamfunn",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Buddhisme\")",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i islamske trossamfunn",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Islam\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i kristne trossamfunn utenfor Den norske kirke",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kristendom\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Medlemmer i andre livssynssamfunn",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08531\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\"),",
              "    FILTER(ALL('Religionlivssyn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Livssyn\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Kvadratmeterpris (kr) brukte eneboliger",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"03364\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Kvadratmeterpris (kr)\"),",
              "    FILTER(ALL('Type'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Brukte eneboliger\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Kvadratmeterpris (kr) nye eneboliger",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"03364\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Kvadratmeterpris (kr)\"),",
              "    FILTER(ALL('Type'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Nye eneboliger\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Bolig"
          },
          {
            "name": "Gjennomsnittlig antall lovbrudd per 1000 innbyggere",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle lovbruddsgrupper\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Andel netto driftsutgifter til sosialsektoren",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Sosialsektoren samlet\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til barnevern",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnevern\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til administrasjon",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Administrasjon, kommune\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til eiendomsforvaltning",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eiendomsforvaltning, kommune\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til barnehage",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til grunnskole",
            "expression": [
              "",
              "",
              "var a = ",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Grunnskole\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel netto driftsutgifter til helse og omsorg",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12362\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Helse- og omsorg\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(a, [Samlede netto driftsutgifter]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Annet lovbrudd",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Annet lovbrudd (inkl. Annet vinningslovbrudd, Eiendomsskade og Seksuallovbrudd)\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Eiendomstyveri",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eiendomstyveri\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Ordens- og integritetskrenkelse",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Ordens- og integritetskrenkelse\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Rusmiddellovbrudd",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Rusmiddellovbrudd\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Trafikkovertredelse",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Trafikkovertredelse\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Vold og mishandling",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"08487\"),",
              "    FILTER(ALL('Lovbruddtype'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Vold og mishandling\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lovbrudd anmeldt per 1 000 innbyggere (årlig gjennomsnitt)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Anmeldte lovbrudd"
          },
          {
            "name": "Valgdeltakelse kommunestyre- og fylkestingsvalg - prosent",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var valgte_region = SELECTEDVALUE('Region'[Kode])",
              "",
              "var valgdeltakelse =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"09475\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Valgdeltakelse i prosent\")",
              ")",
              "",
              "/* Hvis sammenslåingen har skjedd etter valgte_aar 1, ellers 0 */",
              "var skalnullesut =",
              "CALCULATE([Er regionen sammenslått],",
              "    FILTER(ALL('Sammenslåtte Regioner'[GyldigFraDato]),",
              "        IF(",
              "            OR(",
              "                IF(AND(YEAR([GyldigFraDato]) = 2020, YEAR([GyldigFraDato]) - 1 > valgte_aar), 1, 0),",
              "                IF(AND(YEAR([GyldigFraDato]) <> 2020, YEAR([GyldigFraDato]) > valgte_aar), 1, 0)",
              "            ), ",
              "            1, ",
              "            0",
              "        )",
              "    )",
              ")",
              "",
              "return (",
              "    IF(skalnullesut, 0, valgdeltakelse)",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Valgdeltakelse"
          },
          {
            "name": "Blokkleiligheter",
            "expression": [
              "",
              "",
              "CALCULATE([Gjennomsnittlig kvadratmeterpris (kr)],",
              "    FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Blokkleiligheter\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Eneboliger",
            "expression": [
              "",
              "",
              "CALCULATE([Gjennomsnittlig kvadratmeterpris (kr)],",
              "    FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Eneboliger\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Småhus",
            "expression": [
              "",
              "",
              "CALCULATE([Gjennomsnittlig kvadratmeterpris (kr)],",
              "    FILTER(ALL('Boligtype'[Dimensjonsnavn]), 'Boligtype'[Dimensjonsnavn] = \"Småhus\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Andel 18-29 år",
            "expression": [
              "",
              "",
              "var med_atten_tjueni =",
              "CALCULATE([Antall kommunestyremedlemmer],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-29 år\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(med_atten_tjueni, [Antall kommunestyremedlemmer]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Politisk styring og kontrollvirksomhet",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Politisk styring og kontrollvirksomhet, fylkeskommune\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Administrasjon, fylkeskommune\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Eiendomsforvaltning",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eiendomsforvaltning, fylkeskommune\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")",
              "",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Fellesutgifter",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Fellesutgifter, fylkeskommune\"),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Fysisk planlegging, kulturminner, natur, nærmiljø, fylkeskommune",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Fysisk planlegging, kulturminner, natur, nærmiljø, fylkeskommune\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Kultur",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Kultur, fylkeskommune\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Næringsforvaltning",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Næringsforvaltning, fylkeskommune\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Samferdsel",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Samferdsel, fylkeskommune\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Tannhelse",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Tannhelse\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Videregående opplæring samlet",
            "expression": [
              "",
              "",
              "CALCULATE([Samlede netto driftsutgifter FK],",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Videregående opplæring samlet\"",
              "    ),",
              "    FILTER(ALL('Art'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Netto driftsutgifter på funksjon/tjenesteområde\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Samlede netto driftsutgifter",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12364\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Andel uføretrygdede av befolkningen 18-67 år",
            "expression": [
              "",
              "",
              "var valgte_region = SELECTEDVALUE('Alle Data'[Kode])",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var andelufor =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"ØOA01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel uføretrygdede av befolkningen 18-67 år\"",
              "    )",
              ")",
              "",
              "var skalnullesut =",
              "CALCULATE([Er regionen sammenslått],",
              "    FILTER(ALL('Region'[Kode]), [Kode] = valgte_region),",
              "    FILTER(ALL('Sammenslåtte Regioner'[GyldigFraDato]), ",
              "        IF(YEAR([GyldigFraDato]) > valgte_aar, 1, 0)",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        IF(skalnullesut, 0, andelufor),",
              "        2",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Uføretrygdede"
          },
          {
            "name": "Netto driftsutgifter øvrige sektorer",
            "expression": [
              "",
              "",
              "100-",
              "([Andel netto driftsutgifter til administrasjon]",
              "+",
              "[Andel netto driftsutgifter til barnehage]",
              "+",
              "[Andel netto driftsutgifter til barnevern]",
              "+",
              "[Andel netto driftsutgifter til eiendomsforvaltning]",
              "+",
              "[Andel netto driftsutgifter til grunnskole]",
              "+",
              "[Andel netto driftsutgifter til helse og omsorg]",
              "+",
              "[Andel netto driftsutgifter til sosialsektoren])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Kommuneøkonomi"
          },
          {
            "name": "Siktede personer",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"09418\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Siktede personer, bosted\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Folketall",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"07459\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Antall kvinner av befolkningen",
            "description": "Innbyggere kvinner i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kvinner\")",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Antall menn av befolkningen",
            "description": "Innbyggere menn i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Menn\")",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter kjønn"
          },
          {
            "name": "Andel av befolkningen 19 år eller yngre",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Innbyggere 0-19 år], [Folketall]) * 100, 2)",
              "",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Arbeiderpartiet",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Arbeiderpartiet\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Fremskrittspartiet",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Fremskrittspartiet\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Høyre",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Høyre\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Senterpartiet",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Senterpartiet\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Sosialistisk Venstreparti",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Sosialistisk Venstreparti\")",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Venstre",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Venstre\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andre partier",
            "expression": [
              "",
              "",
              "[Valgte representanter] - [Sum utvalgte]"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Kristelig Folkeparti",
            "expression": [
              "",
              "",
              "CALCULATE([Valgte representanter],",
              "    FILTER(ALL('Politisk parti'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kristelig Folkeparti\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel 30-39 år",
            "expression": [
              "",
              "",
              "var med_tretti_trettini =",
              "CALCULATE([Antall kommunestyremedlemmer],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"30-39 år\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(med_tretti_trettini, [Antall kommunestyremedlemmer]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel 40-49 år",
            "expression": [
              "",
              "",
              "var med_forti_fortini =",
              "CALCULATE([Antall kommunestyremedlemmer],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"40-49 år\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(med_forti_fortini, [Antall kommunestyremedlemmer]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel 50-59 år",
            "expression": [
              "",
              "",
              "var med_femti_femtini =",
              "CALCULATE([Antall kommunestyremedlemmer],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"50-59 år\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(med_femti_femtini, [Antall kommunestyremedlemmer]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel 60 år eller eldre",
            "expression": [
              "",
              "",
              "var med_seksti_pluss =",
              "CALCULATE([Antall kommunestyremedlemmer],",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"60 år eller eldre\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(med_seksti_pluss, [Antall kommunestyremedlemmer]) * 100, 2)",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Alle husholdninger",
            "expression": [
              "",
              "",
              "/* Inntekt etter skatt median (kr) */",
              "CALCULATE([Medianinntekt etter skatt],",
              "    FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Alle husholdninger\"",
              "    )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Aleneboende",
            "expression": [
              "",
              "",
              "/* Inntekt etter skatt median (kr) */",
              "CALCULATE([Medianinntekt etter skatt],",
              "    FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Aleneboende\"",
              "    )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Enslig mor/far med barn 0-17 år",
            "expression": [
              "",
              "",
              "/* Inntekt etter skatt median (kr) */",
              "CALCULATE([Medianinntekt etter skatt],",
              "    FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Enslig mor/far med barn 0-17 år\"",
              "    )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Par med barn 0-17 år",
            "expression": [
              "",
              "",
              "/* Inntekt etter skatt median (kr) */",
              "CALCULATE([Medianinntekt etter skatt],",
              "    FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Par med barn 0-17 år\"",
              "    )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Par uten barn, median",
            "expression": [
              "",
              "",
              "/* Inntekt etter skatt median (kr) */",
              "CALCULATE([Medianinntekt etter skatt],",
              "    FILTER(ALL('Husholdningstype'[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"Par uten barn\"",
              "    )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Siktede personer 5-14 år",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"5-14\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 15-17 år",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"15-17\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 25-29 år",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"25-29\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 30-39 år",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"30-39\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 60-150 år",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"60-150\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer uoppgitt alder",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"160-991\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"0-991\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Rammetilskudd fra staten",
            "expression": [
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A800\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Beløp på utvalgte sektorer"
          },
          {
            "name": "Skatteinntekter (fra personer)",
            "expression": [
              "",
              "",
              "var skatt_inntekt_formue =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A870\")",
              ")",
              "",
              "var andre_skatter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"877\")",
              ")",
              "",
              "Return (",
              "    skatt_inntekt_formue + andre_skatter",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Beløp på utvalgte sektorer"
          },
          {
            "name": "Eiendomsskatt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AG10\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Beløp på utvalgte sektorer"
          },
          {
            "name": "Brukerbetaling (Gebyrer og egenandeler)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A600\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Beløp på utvalgte sektorer"
          },
          {
            "name": "Andre inntekter, øremerkede tilskudd fra staten mv.",
            "expression": [
              "",
              "",
              "var andre_overforinger =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD17\")",
              ")",
              "",
              "var andre_statlige_overforinger = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A810\")",
              ")",
              "",
              "var andre_salg_leieinntekter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD34\")",
              ")",
              "",
              "var overforingsinntekter_motytelse_drift = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12328\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD48\")",
              ")",
              "",
              "Return (",
              "    andre_overforinger + andre_statlige_overforinger + andre_salg_leieinntekter",
              "    + overforingsinntekter_motytelse_drift",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Beløp på utvalgte sektorer"
          },
          {
            "name": "Siktede personer 5 år+",
            "expression": [
              "",
              "",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"5-151\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 18-24 år",
            "expression": [
              "",
              "",
              "var atten_tjue =",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"18-20\")",
              ")",
              "",
              "var tjueen_tjuefire =",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"21-24\")",
              ")",
              "",
              "Return (",
              "    atten_tjue + tjueen_tjuefire",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer 40-59 år",
            "expression": [
              "",
              "",
              "var forti_fortini =",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"40-49\")",
              ")",
              "",
              "var femti_femtini =",
              "CALCULATE([Siktede personer], ",
              "    FILTER(ALL('Alder'[Dimensjonskode]), [Dimensjonskode] = \"50-59\")",
              ")",
              "",
              "Return (",
              "    forti_fortini + femti_femtini",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 18-24",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 18 && VALUE([Dimensjonskode]) <= 24)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 18-24 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 5-14",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 5 && VALUE([Dimensjonskode]) <= 14)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 5-14 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 15-17",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 15 && VALUE([Dimensjonskode]) <= 17)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 15-17 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 25-29",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]),",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 25 && VALUE([Dimensjonskode]) <= 29)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 25-29 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 30-39",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]),",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 30 && VALUE([Dimensjonskode]) <= 39)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 30-39 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 40-59",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]),",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 40 && VALUE([Dimensjonskode]) <= 59)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 40-59 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 60-150",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]),",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 60 && VALUE([Dimensjonskode]) <= 150)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 60-150 år], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen i alt",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 5 && VALUE([Dimensjonskode]) <= 150)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer i alt], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Siktede personer per tusen 5 år+",
            "expression": [
              "",
              "",
              "/* Er blank, men får verdier når man spesifiserer År */",
              "",
              "/* Må se på 1.1 neste år for å få riktige tall */",
              "var aar = SELECTEDVALUE('År'[År]) + 1",
              "",
              "/* Befolkning/folketall */",
              "var befolkning = CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 5 && VALUE([Dimensjonskode]) <= 150)),",
              "    FILTER(ALL('År'[År]), 'År'[År] = aar)",
              ")",
              "",
              "Return (",
              "    ROUND(DIVIDE([Siktede personer 5 år+], befolkning) * 1000, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Siktede personer"
          },
          {
            "name": "Antall kommunestyremedlemmer",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"04966\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Medlemmer\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Valgte representanter",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"01182\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Valgte representanter\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel av befolkningen 20-39 år",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Innbyggere 20-39 år], [Folketall]) * 100, 2)",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Andel av befolkningen 40-59 år",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Innbyggere 40-59 år], [Folketall]) * 100, 2)",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Innbyggere per 1.1",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"07459\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere"
          },
          {
            "name": "Sum utvalgte",
            "expression": [
              "",
              "",
              "[Venstre] + [Arbeiderpartiet] +",
              "[Fremskrittspartiet] + [Høyre] + ",
              "[Kristelig Folkeparti] + [Senterpartiet] + ",
              "[Sosialistisk Venstreparti]"
            ],
            "formatString": "#,0",
            "displayFolder": "DEMOKRATI OG POLITIKK;Kommunestyrerepresentanter"
          },
          {
            "name": "Andel av befolkningen 60-79 år",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Innbyggere 60-79 år], [Folketall]) * 100, 2)",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Andel av befolkningen 80 år og over",
            "expression": [
              "",
              "",
              "ROUND(DIVIDE([Innbyggere 80 år og over], [Folketall]) * 100, 2)",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Innbyggere etter alder"
          },
          {
            "name": "Antall virksomheter",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"10309\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Virksomheter\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Sysselsatte i alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"07984\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sysselsatte personer etter bosted\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Sysselsatte"
          },
          {
            "name": "Antall personer 16 år og over med grunnskoleutdanning eller høyere",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09429\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Personer 16 år og over\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Utdanningsnivå"
          },
          {
            "name": "Antall virksomheter: Primærnæring",
            "expression": [
              "",
              "",
              "CALCULATE([Antall virksomheter],",
              "    FILTER(ALL('Næring'[Dimensjonsnavn]), [Dimensjonsnavn] IN ",
              "        {",
              "            \"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\"",
              "        }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Antall virksomheter: Sekundærnæring",
            "expression": [
              "",
              "",
              "CALCULATE([Antall virksomheter],",
              "    FILTER(ALL('Næring'[Dimensjonsnavn]), [Dimensjonsnavn] IN ",
              "        {",
              "            \"Industri\", \"Bygge- og anleggsvirksomhet\"",
              "        }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Antall virksomheter: Tertiærnæring",
            "expression": [
              "",
              "",
              "/* All næring som ikke er primær- eller sekundærnæringer, eller uoppgitt */",
              "var a =",
              "CALCULATE([Antall virksomheter],",
              "    FILTER(ALL('Næring'[Dimensjonsnavn]), [Dimensjonsnavn] IN ",
              "        {",
              "            \"Jordbruk, skogbruk og fiske\", \"Bergverksdrift og utvinning\", ",
              "            \"Industri\", \"Bygge- og anleggsvirksomhet\",",
              "            \"Uoppgitt\"",
              "        }",
              "    )",
              ")",
              "",
              "return (",
              "    [Antall virksomheter] - a",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Antall virksomheter: Uoppgitt",
            "expression": [
              "",
              "",
              "CALCULATE([Antall virksomheter],",
              "    FILTER(ALL('Næring'[Dimensjonsnavn]), [Dimensjonsnavn] IN ",
              "        {",
              "            \"Uoppgitt\"",
              "        }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Virksomheter"
          },
          {
            "name": "Samlede netto driftsutgifter FK",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12368\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Fylkeskommunal økonomi"
          },
          {
            "name": "Gjennomsnittlig kvadratmeterpris (kr)",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var valgte_region = SELECTEDVALUE('Region'[Kode])",
              "",
              "var kvmpris = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), 'Tabeller'[Tabellnummer] = \"06035\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig kvadratmeterpris (kr)\")",
              ")",
              "",
              "/* Hvis sammenslåingen har skjedd etter valgte_aar 1, ellers 0 */",
              "var skalnullesut =",
              "CALCULATE([Er regionen sammenslått],",
              "    FILTER(ALL('Region'[Kode]), [Kode] = valgte_region),",
              "    FILTER(ALL('Sammenslåtte Regioner'[GyldigFraDato]), ",
              "        IF(YEAR([GyldigFraDato]) > valgte_aar, 1, 0)",
              "    )",
              ")",
              "",
              "return (",
              "    IF(skalnullesut, 0, kvmpris)",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Selveierbolig"
          },
          {
            "name": "Medianinntekt etter skatt",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var valgte_region = SELECTEDVALUE('Region'[Kode])",
              "",
              "var medianinntekt =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"06944\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Inntekt etter skatt, median (kr)\"",
              "    )",
              ")",
              "",
              "/* Hvis sammenslåingen har skjedd etter valgte_aar 1, ellers 0 */",
              "var skalnullesut =",
              "CALCULATE([Er regionen sammenslått],",
              "    FILTER(ALL('Sammenslåtte Regioner'[GyldigFraDato]), ",
              "        IF(YEAR([GyldigFraDato]) > valgte_aar, 1, 0)",
              "    )",
              ")",
              "",
              "return (",
              "    IF(skalnullesut, 0, medianinntekt)",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Inntekt etter skatt"
          },
          {
            "name": "Har regionen innført eiendomsskatt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"12503\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Har kommunen innført eiendomsskatt? (ja=1, nei=0)\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "ØKONOMI OG ARBEIDSLIV;Eiendomsskatt"
          },
          {
            "name": "Medlemmer og tilhørige i Den norske kirke",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12026\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Medlemmer og tilhørige i Dnk (antall)\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Tro og livssyn"
          },
          {
            "name": "Er regionen sammenslått",
            "expression": [
              "",
              "",
              "var valgte_regioner = SELECTEDVALUE('Region'[Kode])",
              "",
              "var antallrader =",
              "CALCULATE(COUNT('Sammenslåtte Regioner'[SammenslåingsDato]),",
              "    FILTER(ALL('Sammenslåtte Regioner'[Kode]), [Kode] = valgte_regioner)",
              ")",
              "",
              "return (",
              "    IF (antallrader > 0, 1, 0)",
              ")"
            ],
            "displayFolder": "Testing"
          },
          {
            "name": "Separert",
            "expression": [
              "",
              "",
              "var antall_separerte =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Separert\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_separerte, [Folketall]) * 100, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Enke/enkemann",
            "expression": [
              "",
              "",
              "var antall_enker =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Enke/enkemann\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_enker, [Folketall]) * 100, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Annen sivilstand",
            "expression": [
              "",
              "",
              "var antall_annen =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"03027\"),",
              "    FILTER(ALL('Sivilstand'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Annen sivilstand\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Personer\")",
              ")",
              "",
              "return (",
              "    ROUND(DIVIDE(antall_annen, [Folketall]) * 100, 2)",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Sivilstand"
          },
          {
            "name": "Innbyggere 18-67 år",
            "expression": [
              "",
              "",
              "CALCULATE([Folketall],",
              "    FILTER(ALL('Alder'[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 18 && VALUE([Dimensjonskode]) <= 67))",
              ")"
            ]
          },
          {
            "name": "Innflytting",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09588\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Innflytting\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Flytting"
          },
          {
            "name": "Utflytting",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer]= \"09588\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Utflytting\")",
              ")"
            ],
            "displayFolder": "BEFOLKNING OG DEMOGRAFI;Flytting"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[KS Ung Indikatorer].[Demokrati og politikk],[dbo].[KS Ung Indikatorer].[Befolkning og demografi],[dbo].[KS Ung Indikatorer].[Økonomi og arbeidsliv],[dbo].[KS Ung Indikatorer].[Annet] FROM [dbo].[KS Ung Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "KS Ung Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>134</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Demokrati og politikk</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Befolkning og demografi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Økonomi og arbeidsliv</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Annet</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Domstolene og kriminalitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Innvandringskategori",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Innvandringskategori",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Innvandringskategori].* FROM [dbo].[Innvandringskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Innvandringskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Landbakgrunn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Landbakgrunn",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Landbakgrunn].* FROM [dbo].[Landbakgrunn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Landbakgrunn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kjønn",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kjønn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Antall",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Antall",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Antall].* FROM [dbo].[Antall] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Antall].* FROM [dbo].[Antall] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Antall"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Næring",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Næring",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Næring].* FROM [dbo].[Næring] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Næring].* FROM [dbo].[Næring] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Næring"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Nivå",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Nivå",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Nivå].* FROM [dbo].[Nivå] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Nivå].* FROM [dbo].[Nivå] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Nivå"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Eierstatus",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Eierstatus",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Eierstatus].* FROM [dbo].[Eierstatus] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eierstatus].* FROM [dbo].[Eierstatus] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eierstatus"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Lovbruddtype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Lovbruddtype",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Lovbruddtype].* FROM [dbo].[Lovbruddtype] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Lovbruddtype].* FROM [dbo].[Lovbruddtype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Lovbruddtype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Religionlivssyn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Religionlivssyn",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Religion/livssyn].* FROM [dbo].[Religion/livssyn] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Religion/livssyn].* FROM [dbo].[Religion/livssyn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Religion/livssyn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tettbygdspredtbygd strøk",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tettbygdspredtbygd strøk",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tettbygd/spredtbygd strøk].* FROM [dbo].[Tettbygd/spredtbygd strøk] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tettbygd/spredtbygd strøk].* FROM [dbo].[Tettbygd/spredtbygd strøk] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tettbygd/spredtbygd strøk"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Type",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Type",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Type].* FROM [dbo].[Type] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Type].* FROM [dbo].[Type] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Type"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Politisk parti",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Politisk parti",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Politisk parti].* FROM [dbo].[Politisk parti] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Politisk parti].* FROM [dbo].[Politisk parti] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Politisk parti"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Boligtype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Boligtype",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Boligtype].* FROM [dbo].[Boligtype] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Boligtype].* FROM [dbo].[Boligtype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Boligtype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Husholdningstype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Husholdningstype",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Husholdningstype].* FROM [dbo].[Husholdningstype] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Husholdningstype].* FROM [dbo].[Husholdningstype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Husholdningstype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Sivilstand",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sivilstand",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Sivilstand].* FROM [dbo].[Sivilstand] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sivilstand].* FROM [dbo].[Sivilstand] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sivilstand"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Sammenslåtte Regioner",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "SammenslåingsDato",
            "dataType": "dateTime",
            "sourceColumn": "SammenslåingsDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Sammenslåtte Regioner",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] ",
              "dataSource": "Reporting_Kart"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>70</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SammenslåingsDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SammenslåingsDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sammenslåtte Regioner"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>70</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SammenslåingsDato</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SammenslåingsDato</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Regionsendringer",
        "columns": [
          {
            "name": "gammeltKommunenummer",
            "dataType": "string",
            "sourceColumn": "gammeltKommunenummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "gammeltNavn",
            "dataType": "string",
            "sourceColumn": "gammeltNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "nyttKommunenummer",
            "dataType": "string",
            "sourceColumn": "nyttKommunenummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "nyttNavn",
            "dataType": "string",
            "sourceColumn": "nyttNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "endringsDato",
            "dataType": "dateTime",
            "sourceColumn": "endringsDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Regionsendringer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Regionsendringer].* FROM [dbo].[Regionsendringer] ",
              "dataSource": "Reporting_Kart"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Regionsendringer].* FROM [dbo].[Regionsendringer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Regionsendringer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "CalculatedTable 1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "gammeltKommunenummer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Regionsendringer[gammeltKommunenummer]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(",
                "    VALUES(Regionsendringer[gammeltKommunenummer]),",
                "    FILTER(ALL(Regionsendringer[nyttKommunenummer]), [nyttKommunenummer] = \"3014\")",
                ")"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6764c131-70d7-4d58-87ec-e1be7e87721f",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "71e5ce99-7109-4b3e-85ce-575d842bbe34",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "1727a679-fdf9-482d-83d4-8451a729262f",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "3d4b5eaf-52e7-4e30-9098-a92d9cc94cf9",
        "fromTable": "Alle Data",
        "fromColumn": "Innvandringskategori",
        "toTable": "Innvandringskategori",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "9f18fa73-6ce3-4e25-93d3-468f963d45c4",
        "fromTable": "Alle Data",
        "fromColumn": "Kjønn",
        "toTable": "Kjønn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "6573154d-3676-4f48-b81d-4f0475fa2b32",
        "fromTable": "Alle Data",
        "fromColumn": "Landbakgrunn",
        "toTable": "Landbakgrunn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "18bbd2aa-4900-4509-910a-02c976f5c4de",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "6ef723c4-9df4-4e94-af53-3bd46d6baf18",
        "fromTable": "Alle Data",
        "fromColumn": "Næring",
        "toTable": "Næring",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "99f14b80-da20-4da6-9dae-92d750150620",
        "fromTable": "Alle Data",
        "fromColumn": "Antall",
        "toTable": "Antall",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "28370490-a573-48d2-8fd6-180c1f5661db",
        "fromTable": "Alle Data",
        "fromColumn": "Alder",
        "toTable": "Alder",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "8e53a793-df81-45b0-9898-fe026e6e85ce",
        "fromTable": "Alle Data",
        "fromColumn": "Nivå",
        "toTable": "Nivå",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cd997538-c7f8-4545-b944-cb530bfc5432",
        "fromTable": "Alle Data",
        "fromColumn": "Eierstatus",
        "toTable": "Eierstatus",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cff1f54c-2aed-4e71-9908-c2efb18fe322",
        "fromTable": "Alle Data",
        "fromColumn": "Religion/livssyn",
        "toTable": "Religionlivssyn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "ce88a1d2-a620-4b5d-8927-a1aac3af336e",
        "fromTable": "Alle Data",
        "fromColumn": "Tettbygd/spredtbygd",
        "toTable": "Tettbygdspredtbygd strøk",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "b3219bb5-1efd-4319-ba17-6206e4a00997",
        "fromTable": "Alle Data",
        "fromColumn": "Type enebolig",
        "toTable": "Type",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "c6a56284-b0f3-48bb-ab38-78ab6d78f297",
        "fromTable": "Alle Data",
        "fromColumn": "Lovbruddstype",
        "toTable": "Lovbruddtype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "98ffd7f1-93cb-4536-ab6e-d3ea390c1555",
        "fromTable": "Alle Data",
        "fromColumn": "Art",
        "toTable": "Art",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f451768d-7ea2-44b2-8752-8e1f1da0390f",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjon",
        "toTable": "Funksjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "b2b0ecdc-39d0-49bd-a715-5dc7c3c137d0",
        "fromTable": "Alle Data",
        "fromColumn": "Politisk parti",
        "toTable": "Politisk parti",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "d8a23017-8390-4f32-8e8a-97ab382f411a",
        "fromTable": "Alle Data",
        "fromColumn": "Boligtype",
        "toTable": "Boligtype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "929faa59-070f-4de2-9581-4a0bf7211730",
        "fromTable": "Alle Data",
        "fromColumn": "Husholdningtype",
        "toTable": "Husholdningstype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "13a92742-697b-4105-9f53-65a7d05209b3",
        "fromTable": "Alle Data",
        "fromColumn": "Sivilstand",
        "toTable": "Sivilstand",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}